<%@ Page Title="Home" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Homepage.aspx.cs" Inherits="webapp.Homepage" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <meta name="description" content="Digital Library - Your gateway to knowledge with extensive book collection and community features." />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <!-- Hero Section -->
    <section class="hero-section bg-gradient-primary text-white py-5">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <h1 class="display-4 fw-bold mb-3">Welcome to Digital Library</h1>
                    <p class="lead mb-4">Discover, Learn, and Grow with our extensive collection of books and resources. Join our community of passionate readers and learners.</p>
                    <div class="hero-buttons">
                        <a href="#" class="btn btn-light btn-lg me-3 mb-2">
                            <i class="fas fa-book-open me-2"></i>Browse Collection
                        </a>
                        <a href="#" class="btn btn-outline-light btn-lg mb-2">
                            <i class="fas fa-user-plus me-2"></i>Join Now
                        </a>
                    </div>
                </div>
                <div class="col-lg-6 text-center">
                    <img src="imgs/library-hero.png" alt="Library Illustration" class="img-fluid hero-image" style="max-height: 400px;" />
                </div>
            </div>
        </div>
    </section>

    <!-- Image Carousel Section -->
    <section class="py-5">
        <div class="container">
            <div class="text-center mb-5">
                <h2 class="section-title">Featured Collections</h2>
                <p class="section-subtitle">Explore our curated book selections</p>
            </div>
            
            <div class="carousel-container">
                <div class="carousel">
                    <!-- Carousel items will be generated by JavaScript in Master Page -->
                </div>
                
                <button class="carousel-control prev">
                    <i class="fas fa-chevron-left"></i>
                </button>
                <button class="carousel-control next">
                    <i class="fas fa-chevron-right"></i>
                </button>
            </div>
            
            <div class="carousel-nav">
                <!-- Navigation dots will be generated by JavaScript in Master Page -->
            </div>
            
            <div class="image-counter">
                Image <span id="current-index">1</span> of 10
            </div>
        </div>
    </section>

    <!-- Features Section -->
    <section class="features-section py-5">
        <div class="container">
            <div class="text-center mb-5">
                <h2 class="section-title">Our Features</h2>
                <p class="section-subtitle">Discover what makes our digital library exceptional</p>
            </div>
            
            <div class="row g-4">
                <div class="col-md-4">
                    <div class="feature-card card h-100 border-0 shadow-sm">
                        <div class="card-body text-center p-4">
                            <div class="feature-icon mb-3">
                                <img src="imgs/booksimg.jpg" width="80" class="rounded-circle" alt="Digital Book Inventory" />
                            </div>
                            <h4 class="card-title">Digital Book Inventory</h4>
                            <p class="card-text">Comprehensive digital management system organizing thousands of books with advanced search and categorization features.</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="feature-card card h-100 border-0 shadow-sm">
                        <div class="card-body text-center p-4">
                            <div class="feature-icon mb-3">
                                <img src="imgs/bookserch.png" width="80" class="rounded-circle" alt="Search Books" />
                            </div>
                            <h4 class="card-title">Advanced Search</h4>
                            <p class="card-text">Powerful search functionality allowing users to find books by title, author, genre, keywords, and advanced filters.</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="feature-card card h-100 border-0 shadow-sm">
                        <div class="card-body text-center p-4">
                            <div class="feature-icon mb-3">
                                <img src="imgs/bookreturn.png" width="80" class="rounded-circle" alt="Book Returns" />
                            </div>
                            <h4 class="card-title">Smart Returns</h4>
                            <p class="card-text">Automated return management system with reminders, due date tracking, and seamless book return process.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Banner Section -->
    <section class="banner-section">
        <div class="container-fluid p-0">
            <img src="imgs/bookbk3.png" class="img-fluid w-100" alt="Library Banner" style="height: 300px; object-fit: cover;" />
        </div>
    </section>

    <!-- Process Section -->
    <section class="process-section py-5 bg-light">
        <div class="container">
            <div class="text-center mb-5">
                <h2 class="section-title">Our Process</h2>
                <p class="section-subtitle">Simple steps to join our knowledge community</p>
            </div>
            
            <div class="row g-4">
                <div class="col-md-4">
                    <div class="process-card card h-100 border-0 shadow">
                        <div class="card-body text-center p-4">
                            <div class="process-number mb-3">
                                <span class="number-circle">1</span>
                            </div>
                            <div class="process-icon mb-3">
                                <img src="imgs/libra.png" width="60" alt="Register" />
                            </div>
                            <h4 class="card-title">Register</h4>
                            <p class="card-text">Quick and easy registration process with secure account creation and personalized access to all library features.</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="process-card card h-100 border-0 shadow">
                        <div class="card-body text-center p-4">
                            <div class="process-number mb-3">
                                <span class="number-circle">2</span>
                            </div>
                            <div class="process-icon mb-3">
                                <img src="imgs/data.png" width="60" alt="Community" />
                            </div>
                            <h4 class="card-title">Community</h4>
                            <p class="card-text">Join discussions, share insights, and collaborate with fellow readers in our vibrant community forums and groups.</p>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="process-card card h-100 border-0 shadow">
                        <div class="card-body text-center p-4">
                            <div class="process-number mb-3">
                                <span class="number-circle">3</span>
                            </div>
                            <div class="process-icon mb-3">
                                <img src="imgs/promtr.png" width="60" alt="Publisher" />
                            </div>
                            <h4 class="card-title">Publisher Access</h4>
                            <p class="card-text">Direct access to publisher catalogs, new releases, and exclusive content from leading publishing partners.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Stats Section -->
    <section class="stats-section py-5 bg-primary text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-3 col-6 mb-4">
                    <div class="stat-item">
                        <h3 class="display-4 fw-bold">10,000+</h3>
                        <p class="mb-0">Books Available</p>
                    </div>
                </div>
                <div class="col-md-3 col-6 mb-4">
                    <div class="stat-item">
                        <h3 class="display-4 fw-bold">5,000+</h3>
                        <p class="mb-0">Active Members</p>
                    </div>
                </div>
                <div class="col-md-3 col-6 mb-4">
                    <div class="stat-item">
                        <h3 class="display-4 fw-bold">50+</h3>
                        <p class="mb-0">Publishing Partners</p>
                    </div>
                </div>
                <div class="col-md-3 col-6 mb-4">
                    <div class="stat-item">
                        <h3 class="display-4 fw-bold">24/7</h3>
                        <p class="mb-0">Digital Access</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
</asp:Content>